# Jekyll configuration
name: Le blog de la famille Tomate
title: Le blog de la famille Tomate
email: bruno@lagrappe.net
description: Site de notes sur la musique, les voyages et d'autres sujets de la famille tomate.

timezone: Europe/Paris

# url is currently only used only for the RSS feed in feed.xml
url: https://www.lagrappe.net

baseurl: "" # the subpath of your site, e.g. /blogdd
twitter_username: bam_thomas
github_username:  bamthomas
github: 'bamthomas/lagrappe'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: /:title/
plugins:
- jekyll-paginate
- jekyll-seo-tag
paginate: 9

exclude: ['README.md', 'LICENSE', '*.sh', '.circleci']
encoding: utf-8
